In [1]:
# 稳定性：排序前后两个相等的数的相对位置不变， 如果Ai = Aj, Ai原来在位置前，排序后Ai还是要在Aj位置前
# 下面的 冒泡排序，插入排序，归并排序 都是稳定的
# 下面的 选择排序，快速排序，堆排序, 希尔排序 都是不稳定的

In [1]:
import random
import numpy as np

In [2]:
array = np.arange(10)
print(array)
random.shuffle(array)
print(array)

[0 1 2 3 4 5 6 7 8 9]
[9 7 4 5 0 1 6 8 2 3]


In [4]:
# 冒泡排序
# 时间负责度 O(n^2)

def BubbleSort():
    n = len(array)
    # 遍历数组
    for i in range(n):
        # last i elements are already in place, notice j+1 can not out of bound
        for j in range(0, n-i-1):
            if array[j] > array[j+1]:
                array[j], array[j+1] = array[j+1], array[j]
    return array

list1 = BubbleSort()
print(list1)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# 选择排序
# 在未排序的序列中找到最小的元素，存放在起始位置，
# 再从剩余的排序序列中继续寻找最小的元素
# 放到已排序序列的末尾

def SelectSort():
    n = len(array)
    # 需要n轮比较
    for i in range(n):
        # min_idx记录最小值的下标
        min_idx = i
        # 每轮比较n-i个
        for j in range(i+1, n):
            if array[min_idx] > array[j]:
                min_idx = j
        if min_idx != i:
            array[i], array[min_idx] = array[min_idx], array[i]
    return array

random.shuffle(array)
list2 = SelectSort()
print(list2)


[0 1 2 3 4 5 6 7 8 9]


In [9]:
# 插入排序
# 第一个待排序序列第一个元素看为有序序列，把第二个元素到最后一个元素当初是非排序序列
# 从头到尾扫描非排序序列，将扫描到的每个元素插入有序序列的适当位置

# 因为插入排序是从后往前遍历已经排序好的序列，相同元素不会改变位置，所以为稳定排序
# 空间复杂度：它是在原序列上进行排序，o(1)
# 时间复杂度：o(n^2)

def insertSort():
    n = len(arr)
    #  [0]的元素默认为有序
    # [1,2...,n-1] 默认为待排序
    for i in range(1, n): 
        # 记录要插入的元素，不然会被覆盖
        tmp = arr[i] 
        # 遍历已经排序好的数组
        # 当前元素小于排序好的元素，就移动到下一个位置「即从右向左移动一位」
        j = i  
        while (j>0 and arr[j-1] > tmp): 
            arr[j] = arr[j-1] # 相当于往后移一位
            j = j-1
        if (j!=i):
            arr[j]=tmp
    return arr
  
arr = [1, 5, 3, 8]
insertSort()

[1, 3, 5, 8]

In [10]:
# 分析插入排序法
# arr = [8, 1, 4]
# 已经排好序的arr[:1]=[8], 待排序的arr[1:]=[1, 4]
# tmp = arr[i] = 1
# j = 1
# while (1>0 and arr[0]>tmp): 进入循环
#    arr[1] = arr[0] 
#    j = 0
# j=0 退出循环
# if 1!=0:
#    arr[0]=tmp
# arr[:2] = [1, 8], 待排序的arr[2:]=[4]
# tmp = arr[2] = 4
# j = 2
# while (2>0 and arr[1]>tmp): 进入循环
#    arr[2] = arr[1]
#    j=1
# arr[0]<tmp 退出循环
# if 2!= 1:
#    arr[1]=tmp
# 得到排序好的arr=[1, 4, 8]

In [7]:
# 希尔排序
# 插入排序的改进版本，是一种非稳定的排序算法
# 又称为“缩小增量排序”，增量是相对比较的两个元素之间的距离，当增量减小为1，算法终止。
# 将整个序列分组，对分组后的内容进行插入排序，逐步完成排序

# 相同元素可能分到不同的组中，因此两个相同的元素就可能调换相对位置，故不稳定
# 空间复杂度：整个排序是在原数据上进行操作，为o(1)


def shellSort():
    n = len(array)
    gap = int(n/2)
    while (gap > 0):
        for cur in range(gap, n):
            i = cur
            while i >= gap and array[i-gap] > array[i]:
                array[i-gap], array[i] = array[i], array[i-gap]
                i = i-gap
        gap = int(gap/2)
    return array

list_ = shellSort()
print(list_)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 归并算法
# 1.申请空间
# 2.设定两个指针，最初位置在两个已经排序的起始位置
# 3.选择相对较小的元素放入合并空间，并移动指针到下一位置，
# 重复步骤三，直到某一指针达到序列尾
# 另一序列的所有元素直接复制到合并序列的尾部

In [14]:
# divide and conquer, 
# 1. 将原问题分解为若干个规模更小但结构与原问题相似的子问题
# 2. 递归地解这些子问题，然后将这些子问题的解组合为原问题的解。

# 归并排序 

# 合并
def merge(left, right):
    result = []
    i = 0 
    j = 0
    while(i < len(left) and j < len(right)):
        if left[i] < right[j]:
            result.append(left[i])
            i = i+1
        else:
            result.append(right[j])
            j = j+1
    if i < len(left):
        result.extend(left[i:])
    if j < len(right):
        result.extend(right[j:])
    return result

def mergeSort(arr):
    if len(arr) < 2:
        return arr
    
    middle = len(arr)//2
    # 左半部分拆分
    left = mergeSort(arr[:middle])
    # 右半部分拆分
    right = mergeSort(arr[middle:])
    # 合并
    result = merge(left, right)
    return result

array2 = np.arange(6)
random.shuffle(array2)
print(array2)
list5 = mergeSort(array2)
print(list5)


[4 0 5 2 3 1]
[0, 1, 2, 3, 4, 5]


In [26]:
# 快速排序
# divide and conquer O(n logn)
# partition（分区）：比pivot（基准）值小的放在前面，比pivot值大的放在后面
# pseudo code
def quickSort(arr):
    less = []
    pivotlist = []
    more = []
    if len(arr) <= 1:
        return arr
    
    pivot = arr[0]
    pivotlist.append(pivot)
    for i in range(1, len(arr)):
        if arr[i] < pivot:
            less.append(arr[i])
        else:
            more.append(arr[i])
            
    less = quickSort(less)
    more = quickSort(more)
    result = less+pivotlist+more
    return result

arr = [3, 2, 8, 5]
quickSort(arr)
            
    

[2, 3, 5, 8]

In [10]:
# 堆排序

# 堆是一种完全二叉树「除了最后一层以后堆其他每一层都被完全填充，并让所有借点都保持向左对齐」
# 堆可以分为大根堆和小根堆
# 「大根堆」每个节点的值都大于等于左右孩子节点的值，k_i >= k_(2i) and k_i >= k_(2i+1)
# 「小根堆」每个节点的值小于等于左右孩子节点的值, k_i <= k_(2i) and k_i <= k_(2i+1)
# 主要考虑1. 构造大/小根堆 2. 输出堆顶元素， 如何使剩下的元素维持性质

def heapify(arr, n, i):
    largest = i
    left = 2*i + 1
    right = 2*i + 2
    
    if left < n and arr[largest] < arr[left]:
        largest = left
    
    if right < n and arr[largest] < arr[right]:
        largest = right
    
    if largest != i:
        arr[largest], arr[i] = arr[i], arr[largest]
        heapify(arr, n, largest)

def heapSort(arr):
    n = len(arr)
    
    for i in range(n, -1, -1):
        heapify(arr, n, i)
    
    for i in range(n-1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]
        heapify(arr, i, 0)

array2 = np.arange(6)
random.shuffle(array2)
print(array2)
heapSort(array2)
print(array2)

[4 3 0 1 2 5]
[0 1 2 3 4 5]


In [11]:
# deque 为了实现插入和删除操作的双向列表，适用于队列和栈
from collections import deque
q = deque(['a', 'b', 'c'])
q.append('x')
q.appendleft('y')
q

deque(['y', 'a', 'b', 'c', 'x'])

In [13]:
# 计数器
L = 'abracadabra'
def histogram(L):
    d = {}
    for x in L:
        if x in d:
            d[x] += 1
        else:
            d[x] = 1
    return(d)

print(histogram(L))

from collections import Counter
print(Counter(L))

counts = dict()
for i in L:
    counts[i] = counts.get(i, 0) + 1 #.get allows to specify a default value if the key does not exist
print(counts)

{'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1}
Counter({'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1})
{'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1}


In [14]:
# 计数排序
# 将输入的数据值转化为键存储在额外开辟的数组空间里，输入的数据必须有确定的范围
# bucket 统计输入的数值出现的次数

def countSort(nums):
    bucket = [0]*(max(nums) + 1)
    output = [0]*(len(nums))
    for num in nums:
        bucket[num] += 1
    i = 0
    for j in range(len(bucket)):
        while bucket[j] > 0:
            output[i] = j
            bucket[j] -= 1
            i = i + 1
    return output

array = [1, 4, 3, 6, 2]
print(countSort(array))  

[1, 2, 3, 4, 6]


In [15]:
# 桶排序
# 数组划分为n个大小相同的bucket，space = (max - min + 1)/ 桶数， 每个区间各自排序最后合并

def bucket_sort(arr):
    buckets = [0] * (max(arr) - min(arr) + 1)
    for i in range(len(arr)):
        # 桶的序号i本质是原数列中相应的数值与数列最小值的差值 
        buckets[arr[i] - min(arr)] += 1
    b = []
    for i in range(len(buckets)):
        if buckets[i] != 0:
            # i + min(arr) 是原数列的序号
            b += [i + min(arr)] * buckets[i]
    return b

array = [1, 4, 3, 6, 2]
print(array)
print(bucket_sort(array)) 

[1, 4, 3, 6, 2]
[1, 2, 3, 4, 6]


In [16]:
# 基数排序
# 对个位 -- 十位 -- 百位 依次排序，最终得到有序序列
def radix_sort(array, d): # d 表示轮数
    for i in range(d):
        s = [[] for i in range(10)]
        for j in array:
            s[int(j / (10 ** i)) % 10].append(j)
        re = [a for b in s for a in b]
    return re

array = [10, 22, 15, 40]
print(radix_sort(array, 2))

[10, 15, 22, 40]
